#!/bin/sh -e

STOP_REQUIRED=false
REMOVE_SERVICE=false

case "$1" in

    remove)
        STOP_REQUIRED=true
        REMOVE_SERVICE=true
    ;;
    upgrade)
        if [ "$RESTART_ON_UPGRADE" = "true" ]; then
            STOP_REQUIRED=true
        fi
    ;;
    deconfigure|failed-upgrade)
    ;;

    *)
        echo "pre remove script called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Stops the service
if [ "$STOP_REQUIRED" = "true" ]; then
    echo -n "Stopping Okapi service..."
    if command -v systemctl >/dev/null; then
        systemctl --no-reload stop okapi.service
    fi
    echo " OK"
fi

if [ "$REMOVE_SERVICE" = "true" ]; then
    if command -v systemctl >/dev/null; then
        systemctl disable okapi.service > /dev/null 2>&1 || true
    fi
fi

exit 0
